#!/usr/bin/python

import sys
import socket

if len(sys.argv) < 5:
    print("Syntax: %s <ip-address> <protocol> <port> <message>" % sys.argv[0], file=sys.stderr)
    sys.exit(1)

ip_addr = sys.argv[1]
proto = sys.argv[2]
port = int(sys.argv[3])
msg = sys.argv[4]

if proto == 'udp':
    print("UDP target IP: %s" % ip_addr)
    print("UDP target port: %s" % port)
    print("message: %s" % msg)

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.sendto(msg.encode(), (ip_addr, port))

if proto == 'tcp':
    print("TCP target IP: %s" % ip_addr)
    print("TCP target port: %s" % port)
    print("message: %s" % msg)

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((ip_addr, port))
    sock.send(msg.encode())
    sock.close()

sys.exit(0)
